#import "header.typ": *
#import "template.typ": template
#show: template

#align(center, text(24pt)[
	*Examples for english essays*
])

#outline()
  #show heading: set block(above: 1.4em, below: 1em)
  #show heading.where(level: 2): it => [
  	#set text(font: "IBM Plex Serif")
  	//#pagebreak()
  	#if type(it.numbering) != none [
  		#counter(heading).display(it.numbering)
  	]
  	#it.body
  ]
  #show heading.where(level: 1): it => [
  	#set text(font: "IBM Plex Serif")
  	#pagebreak()
  	#if it.numbering != none [
  		#counter(heading).display(it.numbering)
  	]
  	#it.body
  ]
#set heading(numbering: "I.A.a")

#set par(justify: true)

= File 1 : Science

== Science & Politics 

$=>$ *MAGA's assault on science* : _May 2025_ : In months, the Trump administration has cancelled thousands of research grants and witheld billions of dollar from scientists. They say that science has become inefficient and that scitentists have been captured by groupthink, especially when it comes to DEI. They are suspected to be pushing a "woke" agenda but is also undermining researches for public-health and climate

$=>$ *American innovation going down* : _May 2025_ : With all of its budget cuts and it's cancelation of grants, MAGA is destroying the possibility for its citizens to innovate and is thus shooting it's own foot in the current race for tech innovation

$=>$ *America's brightest minds will walk away* : _April 2025_ : Due to all these cuts, many young promising people are choosing to leave ; they need to choose between leaving the US or leaving science

$=>$ *Europe to burned Amecian scientists : We'll take you in* : _April 2025_ : As scientists are trying the leave the USA, Europe is encouraging them to come to european countries to continue their researchs. To achieve this, scientists wanting to leave the US for Europe are offered grants of up to €4.5 millions for instance.

== Trust in science

$=>$ _November 2024_ : Republicans and republican leaning citizens are a lot less likely to trust science and scientists, will it be in term of their influence on public policy debate, their ability to make good decisions, or in the confidence for their judgments

$=>$ *Trump's 'gold strandard' for science manufactures doubt* : _July 2025_ : Trump's executive order for 'Restoring Gold Strandard Science' is officialy meant to unsure that federal decisions are informed by the most credible, reliable, and impartial scientific evidence available. However, in practive, it gives political figures the authority to decide which subject or study is or isn't 'scientific enough' and what is the proper 'scientific integrity' required.

$=>$ *This phrase was meant to increase trust in science. It backfired* : _August 2025_ : Scientists are partially to blame for the drop in public trust due to the 'Follow the science' phrase. It was meant to inspire confidence. However, science is evidence, not instructions. Thus, treating it as something to be followed shut down dialogue and dismissed all critics as 'anti-science'. We need to be honsest about what science can and can't tell. For instance, the Covid policies were officialy regarded as absolute truth -- essential and nonnegotiable. However, it became evident later that it wasn't and such rigidity turned healthy skepticim into angry defiance.

$=>$ *Fraudulent scientific papers are rapidly increasing. Study finds* : _August 2025_ : A team of researchers found evidence of shady organisations churning out fake or low-quality studies on an industrial scale, threatening the integrity of many fields. Science rely on trust and these outputs are crushing public trust toward science. With more and more graduate students being trained, the competition for a limited number of research jobs sharpened. Because of this, the incentive is now for publishers to publish more and more. 

== Diversity in sicence 

$=>$ *Donald Trump's 'war on woke' is fast becoming a war on science* : _March 2025_ : Trump's attack on DEI have been intense. All DEI programmes within public bodies have been ended and private contractors face cancellation if they don't comply. Any government-funded research is being held back if they include prohibited words such as 'gender', 'pregnant person', 'women', 'elderly', or 'disabled'. Grants are being cancelled if they adress DEI in any form. The notion that DEI involved putting group membership before ability and leads to the appoinment of incompetent candidates is a misrepresentation of what DEI initiatives are all bout. They are about ensuring that less competent members of the most privileged groups are not advantaged over more competent members of less privileged groups.

$=>$ *'Alarm bells' : why are Australian boys doing better than girls in maths and science ?* : _December 2024_ : It's the gap at earlier stages of schooling -- in year 4 -- that really caused the most concern. Internationally, Australia recorded the equal-widest gender gap alongside France in year 4 maths achievment. Sociolgy researchers says the persistence of the gender gap in science and mathematics needed to be viewed in big picture terms -- which were cultural rather than biological : 'kids will do what the culture is guiding them to do'. The challenge is to rewire narratives of science and maths as a 'boring and difficult' pursuit to something that benefits humankind.

== Space exploration

$=>$ *How Nasa's Artemis accords are laying the ground for global space cooperation* : _October 2024_ : Nasa has matched its giant leaps in space with less prominent, but equally significant, smaller steps on the ground, signing almost a quarter of the world's nations to the Artemis Accords, a global alliance settling guiding principles for the peaceful future exploration of deep space. A diverse range of partners will be crucial : prior collaboration between nations spawned the ISS, but the scale of the Artemis project is unprecedented. 'At their core, the Artemis Accords are a preemptive strike against conflict and to ensure we have a peaceful future. As we crafted them, we wanted to ensure they were as inclusive as possible, that any nation which wanted to support reponsible, safe and sustainable exploration could do so. 

= File 2 : Media

== Press freedom

$=>$ *As US dismantles voice of America, rival powers hope to fill the void* : _June 2025_ : The Trump administration set out to dismantle its global influence and information infrastructure, include media outlets that had helped market the US as the wold's moral and cultural authority. The federally funded network reports in countries with limited press freedom. Thus, officials in China, Hungary, Russia, Cambodia or Cuba welcomed the cuts. US rivals have moved to commandeer the communications space abandoned by the Americans. A British former official at NATO on this topic : 'The soft power suicide of the US will be incomprehensible to future historians who will be dumbfounded in their attempts to explain why the global leader voluntarily wrecked one of its greatest national assets.'

$=>$ *Having risked my life in war zones for the BBC, i know this : cuts to the World Service will be disastrous* : _May 2025_ : The British government has made two decision : a severe cut in foreign aid and a similarly severe reduction in Foreign Office support for the BBC World Service. The government which passed theses decisions was supposedly a progressive government. However, it doesn't seem progressive but cheap and reactionary.  'Millions of children globally rely on UK aid to survive and have never needed it more'. 

== Media neutrality

$=>$ *Scientific American didn't need to endorse anybody* : _September 2024_ : Scientific American haw been a mainstay of sicence and technology journalism in the US. The decision to break with tradition and endorse Kamala Harris is a mistake, as was its endorsment of Joe Biden. Their motivation to do so is pretty self-explanatory, however a magazine devoted to science should not take sides in a political contest. Firstly, it doesn't need to endorse anyone : the readers of a magazine such as it are likely people who have a good enough grasp  of the situation to not need this. Moreover, an endorsment such as this one will reduce the trust from the Trump supporters that do read it.

$=>$ *Young UK journalists lean towards activist roles, away from objectivity -- new survey shows* : _April 2025_ : The role of journalists has been changing for some time now. Due to the rise of social media, journalists no longer hold the monopoly on informing the public and holding the powerful to account. Nor do they keep their role as exclusive gatekeepers of news. We (a survey on a sample of 1.13k UK journalists) found a notable shift in which roles journalists emphasise over others. While they still consider their traditional roles to be essential, many appear to be leaning more towards activist roles, and away from roles linked to objectivity.

$=>$ *The Washington Post will ask some sources to annotate its stories* : _June 2025_ : The Washington Post, facing serious financial shortfalls, has spent the past year working on new ways to draw more readers to its site, and encourage those who come to spend more time there. Executives rolled out "Ask The Post AI", a tool that answers readers' questions using published works from The Post The program will also allow people identified by name in an article to comment on it. The aim is to keep readers on the site -- instead of having them shift to social media platforms like X and Facebook to have a conversation about a story. 'Sources sometimes feel like their words are distorted in the journalistic process. This will give them an avenue to make their message more clear'. However, 'most of the sources who talk to The Washington Post are very powerful people who are trying to use their power to shape the country in a way they see fit, and they are masters of manipulation when it comes to messaging and communication'.

== Misinformation

$=>$ *At least wo newspapers syndicated AI garbage* : _May 2025_ : At first glance, 'Heat index' appears as inoffensive as newspaper features get. A 'summer guide' sprawling across more than 50 pages. The feature, which was syndicated over the past week in both the Chicago Sun-Times and The Philadelphia Inquirer, contains '303 Must-Dos, Must-Tastes, and Must-Tries'. Yet, close readers of the guid noticed that something was very off. 'Heat Index' went viral when people pointed out that its guide matched real authors with books they hadn't written -- a hint that the story may have been composed by a chatbot. The author explained that he had asked the AI to help him come up with book recommendations. This time, at least, he did not actually check the chatbot's work.

$=>$ *Can people be persuaded not to believe disinformation ?* : _March 2025_ : Thomas Costello at the MIT published a study of what happens when ChatGPT attempts to talk self-professed believers in conspiracy theories out they peliefs. The study, reduced the self-reported strenght of their beliefs by 20% after 3 rounds of conversation. A fourth of the participants disavowed their beliefs entirerly. Costello believes chatbots work where humans fail because they offer rational responses instead of
letting emotions get the better of them. What’s more, they are able to comb through their extensive training
data to offer precise counter-arguments, rather than the generalised ones humans often reach for in debates.

$=>$ *The Internet is worse than a brainwashing machine* : _January 2025_ : Social medias are able to rewrite history like an Orwellian Minitrue. For instance, even just a few days after the January 7 attack on the Capitol, republicans tried to change the story of what really happened to justify their behavior, and ti works. The internet may function not so much as a brainwashing machine but as a justification machine.

== Social media

$=>$ *Zuckerberg fired the fact-checkers. We tested their replacement* : _August 2025_ : When a hoax about Trump went viral, (I) went on social media to try to set the record straight. (I) drafted a note debunking images claiming to show Trump sleeping during the ceremony, with proofs. None of that mattered, the community note never got added to a post because not enough other uers voted it was 'helpful'. Over four months, (I)'ve drafted 65 notes debunking conspiracy theories, 3 of them got published. Zuckerberg fired professional fact-checkers, leaving users to fight falsehoods with community notes.

$=>$ *Australia's social media ban won't protect kids -- it'll put them more at risk* : _December 2024_ : Australia has recently made the decision to ban children under 16 from social media -- a policy which the government will enforce via untersed age verification (AV) technology. The move has reignited debates about balancing online safety with privacy and freedoms. Efforts to protect children must not rely on thousands of websites globally to implement controls that are far from perfect to begin with. It is absurd to sacrifice privacy, fundamental rights, and safety on the altar of an unachievable kit. Website-based AV also create new security risks. By requiring websites to store vast amounts of personal data, they become lucrative targets from hackers.

$=>$ *Everything the right -- and the left -- are getting wrong about the Online Safety Act* : _August 2025_ : Last week, the UK's Online Safety Act came into force. Disdain from the right isn't surprising. The companies will now have to assess the risk their platforms pose of disseminationg the kind of racist misinformation that fuelled last year's summer riots. What does the act actually do ? It requires online services to assess the risk of harm -- whether illegal content such as childs sexual abuse material, or, in the case of service accessed by children, content such as porn or suicide promotion -- and implement proportionate systems to reduce those risks. Rather than making decisiosn to remove content reactively, or in order to appease politican, tech companies will now need to demonstrate they have taken reasonable steps to prevent this content from appearing in the first place.

= File 3 : Politics

== Young voters

$=>$ *How young voters helped to put Trump in the White House* : _May 2025_ : Millennials & Gen Z are the most diverse and educated generations in American history and long thought to favour the Democratic Party. However, their long-standing advantage over the Republican Party was reduced by nearly two-thirds. Younger voters appear highly sensitive to economic pressure. One reason all groups of young people swung against the Democrats in 2024 seems to be their perceptions of the economy. 18-19 y.o gave Biden a net rating of -23% on his handling of inflation. Yet economic stress is not the only explanation : they are also more likely to consume non-traditional news

$=>$ *How COVID pushed a generation of young people to the right* : _February 2025_ : One cross-county analysis foud that people who experience epidemics between the ages of 18 and 25 have less confidence in their scientific and political leadership Another way that Covid may have accelerated young people's rightward shift around the world by dramatically reducing their physical-world socializing. 

$=>$ *What happens when 16 y.o. get the vote ? Other countries are already seein the benefits* : _July 2025_ : Voting age to 16 for all UK elections ? In 1969, was the first to lower from 21 to 18. A lower voting age is unlikely to change election outcomes : 16-17 make up 1.5%-5% of population. In the longer term, including 16-17 y.o in the elecorate might make democracy more resilient. In Austria and Latin America, young people who were enfranchised at 16 or 17 were more satisfied with democracy and democratic institutions -- parliament or political parties. 

$=>$ *Votes for 16 y.o. ? Sorry, but I'm not convinced* : _April 2025_ : 16 y.o. are great fun but they are not grown up. They cannot marry in England and Wales, drive, smoke, get a tattoo or buy alcohol on their own.
 Why has Keir Stermer told he intends to allow them to vote in UK elections ? The only plausible answer is that he hopes they will vote for him. Educational problem : The one thing that might excuse the government’s cynicism is a programme to prepare teenagers for their new responsibility. The tyranny of academic GCSEs and exam culture should be suspended, if not for ever, then at least for one day a week, to be replaced by compulsory civic awareness. This should embrace an introduction to peace and war, national politics, local government, the law, practical economics and the handling of money. […] I know teachers who genuinely think it is not their job to “teach” a world outside education. They see no need to educate young people in how to relate to one another, work in groups or keep their minds and bodies in good shape. They see no reason to teach self-presentation or expression, the new skills of oracy so crucial to getting on in a creative career. Teachers seem to think all this is for parents, not schools, even when they know it is not true. The school curriculum is in the dark ages. The truth of the matter is that teenagers are acquiring these skills and attitudes from social media. It is online that they are gaining a whole new context for their personal and social lives. They are doing so from the worst possible sources: biased, uncensored, unmediated and unregulated. It must be the worst preparation for that most sacred of democratic rituals – the vote. This is the grim reality of Starmer’s new social contract.

== Policy in the US

== US Foreign policy

$=>$ *Trump and the end of American soft power* : _March 2025_ : Because this attraction — soft power — is rarely sufficient by itself, leaders can find hard power more tempting. But in the longer term, soft power often prevails.  nation’s soft power rests upon its culture, its values and its policies when they are seen as legitimate10 by others. That legitimacy is affected by whether a nation’s actions are perceived as congruent with or contradicting widely held values. President Donald Trump does not understand soft power. His background in New York real estate gave him a truncated view of power limited to coercion and transactions. How else can one explain his bullying of Denmark over Greenland, his threats to Panama, which outrage Latin America, or his siding with Vladimir Putin over Ukraine, which weakens seven decades of the Nato alliance — not to mention his dismantlement of the US Agency for International Development (USAID) that John F Kennedy created? All undercut American soft power.

== Politics in the UK

$=>$ *How Nigel Farage's Reform UK party uphended British politics* : _May 2025_ : For more than a century, power in Britain has changed hands intermittently between Labour and the Conservatives. However, with 30% of projected national shares (English council elections), Reform UK tounced both these parties. Most of Farage's campaign was inspired by American. His main pledge was 'DOGE in every country'. Instead of hyping the local elections into a battle for the fate of the nation, Refrom focused on bin collections, reasoning that voters were less interested in ideology than the delivery of basic services. In the final week, Farage headed to Dover to decry the 37k migrants who arrived in Britain illegally via the English Channel the year prior and pledged to introduce a 'minister for deportation'. Refom won 677/1641 wards and becam	e the largest party on 14/23 councils. The Tories lost 676 councillors and now faces a total wipeout, with Reform, Labour and the Liberal Democrats on the left eroding every part of its aging electoral base. Much like the Gaullists in France, the traditional party of the British center-right risks being consigned to the history books by a brash new upstart.

== UK Foreign Policy

$=>$ *Starmer EU 'reset' risks pleasing no one* : _May 2025_ : Keir Starmer has just wrapped up his press conference with European Commission chief Ursula von der Leyen. The Prime Minister sought to bang the drum for his EU reset, citing his three 'driving principles': more jobs, lower costs and enhanced border control. Starmer boasted that his deal ensures 'unprecedented access' to the EU market, the best of any country outside of the EU or Efta’, while ensuring Britain remains outside the single market and customs union, with no return to freedom of movement. There are three aspects of this deal that could provoke a significant political backlash. The first is the end of checks on agricultural exports from the UK, providing there is 'timely dynamic alignment' with EU rules and standards. Britain can 'contribute appropriately' to the formulation of rules and standards – but it has no right of veto. The second is on fishing: the EU will be given 'full, reciprocal access' to UK waters until June 2038 – a period three times longer than the four-year deal many commentators thought likely. The third is the emissions trading scheme, which risks handing the EU control over UK industrial policy.

= File 4 : Society

== Culture wars

$=>$ *New state laws are fueling a surge in book bans* : _September 2024_ : State and local governments are banning books at rates far higher than before the pandemic. Books have been challenged and removed from schools and libraries for decades, but around 2024, these instances began to skyrocket, fanned by a network of conservative groups and the spread on social media of lists of titles some considered objectionable. Over 10k books were removed, at least temporarily, from public schools in the 2023-24 school year, almost 3x as many removals as the year before. About 8k of those bans came from just Florida and Iowa, here newly implemented state laws led to large numbers of books being removed from the shelves while they were assesd. The law in Iowa, which went into effect in 2023, prohibits any material that depicts sexual acts from all K-12 schools, with the exception of religious texts. It also limits instruction about gender and sexual orientation until seventh grade. In Florida, a law that took effect before the 2023-24 school year said that any book challenged for “sexual conduct” must be removed while it is reviewed.

$=>$ *'For £3k you can be told how guilty you should be' : Why members are deserting the National Trust* : _July 2025_ : The National Trust has become a lightning rod for criticism over its attempts to 'decolonise' its properties and foster social justice activism, and for placing historical links with the slave trade at the forefront of its conservation work. 'I’ve been going to National Trust properties for decades so my criticism is that they often ignored the history of their properties. No context provided, very few labels on exhibits, and it didn’t care to explain its history to its visitors,” says the professor, who stood as a candidate for the National Trust Council last year.' And then suddenly, after Black Lives Matter, it became interested.

== Civil right protests

$=>$ *Just Stop Oil to end disruptive protests with final demonstration date announced* : _March 2025_ : Environmental campaign group Just Stop Oil announced it will cease disruptive action, following a final protest in Parliament Square on 26 April. The campaign group revealed it would be 'the end of soup on Van Goghs, cornstarch on Stonehenge and slow marching in the streets' as the group plans to 'hang up the hi vis' and stop direct action. The announcement comes after new laws have made it increasingly difficult to carry out disruptive protests. In particular, new offences of interfering with key national infrastructure, including “locking on” and a revision of the law around causing a public nuisance, have seen climate activists given long jail terms.

$=>$ *We criminalise the political stunt at our peril. It is a crucial art form that is impossible to ignore* : _August 2025_ : We must ask ourselves: how would the heroic suffragettes or the remarkable Greenham Common women be regarded if active today? The answer is simple: they would be locked up. Just as they were locked up then. A century ago, women chained themselves to railings, set fires, endured prison and changed the world, and we celebrate their victories without thinking too hard about their methods. Yet today’s laws would criminalise them on sight. Yet the cycle is always the same. At the time, protests are demonised, particularly by the right, who instinctively oppose change. Later, the very same acts are reappraised, rehabilitated or even lauded. The suffragettes, once branded terrorists, are now national heroines. The Greenham women, once derided as cranks in cardigans, are now honoured for their foresight. Time transforms outrage into heritage. Today, with Palestine Action banned and Extinction Rebellion dismissed as a nuisance, we’re told that only 'lawful protest' is legitimate. But the suffragettes would fail that test, and so would Greenham.

== Racial justice

$=>$ *Five years after Floyd* : _May 2025_ : We look at what has changed since George Floyd’s murder. Five years ago this Sunday, Minneapolis police officers killed George Floyd. His murder set off protests and riots across the country. Demonstrators called for sweeping changes to policing and remedies for what they described as systemic racism in law enforcement. In a few cities, the federal government intervened. It investigated and publicized police abuses,
pressuring local governments into court-enforced consent decrees. These pacts forced police departments to make specific changes and let federal officials and court monitors track how the policies worked over time. Meanwhile, killings by police officers rose from just over 1,000 in 2019 to around 1,200 in 2024. Officers killed Black Americans at nearly three times the rate that they killed white Americans, roughly the same proportion as before. So why didn’t much change? Experts cite two reasons. First, lawmakers did not embrace all the proposed changes. Ohio, Minnesota and Missouri, for example, rejected more than 98 percent of the proposals that came before their legislatures, according to the Brookings Institution. A bipartisan effort in Congress also collapsed. Second, to the extent lawmakers acted, the changes didn’t go far enough to transform the nature of American policing.

== Gender Equality

= File 5 : Environment

== Climate diasters

$=>$ *20 years after Hurricane Katrina : Could cuts to disaster preparedness leave the US vulnerable again ?* : _August 2025_ : 20 years before, Hurricane Katrina ripped into Louisiana and left New Orleans flooded. ~2k people died and it reshaped how the country responds to disasters. But the systems built in Katrina's wake are now under threat. Scientists and emergency managers are warning that cuts to forecasting and federal response systems risk leaving the US exposed in the midst of hurricane season, and as climate change fuels ever stronger storms. Built by the Army Corps of Engineers to help ships navigate the Mississippi River, the flood walls and concrete levees surrounding the city failed, leaving 80 per cent of it submerged for weeks. The scale of the failure forced many changes. FEMA was restructured. And NOAA launched a major research effort to sharpen its hurricane forecasts. New levees were built to protect cities from floodwaters. n the last three years alone, predictions about the tracks hurricanes will follow have improved 8% and intensity forecasts 10%, according to Ocean Conservancy. Those gains have come from long-term investment. NOAA’s Hurricane Forecast Improvement Project, launched in 2007, built the research backbone for better models and data. But all of this depends on NOAA’s full system being operational – its satellites, ocean sensors, planes, supercomputers and data from international partners. US lawmakers are now weighing cuts that would slash that system and reduce the staff who oversee it.

$=>$ *Climate disasters in first half of 2025 costliest ever on record, research shows* : _October 2025_ : The first half of 2025 was the costliest on record for major disasters in the US, driven by huge wildfires in Los Angeles and storms that battered much of the rest of the country, according to a climate non-profit that has resurrected work axed by Donald Trump’s administration that tracked the biggest disasters. The mounting cost of fires, storms, hurricanes, drought and floods – all worsened by the human-caused climate crisis – was charted over the previous 45 years by the National Oceanic and Atmospheric Administration (Noaa), until the Trump administration “retired” the dataset in May, citing “evolving priorities, statutory mandates and staffing changes”. 

== US climate policy

$=>$ *Supreme Court narrow scope of environmental reviews* : _May 2025_ : The Supreme Court on Thursday unanimously narrowed the scope of government-required environmental reviews for major infrastructure projects, overturning a lower-court block on a rail line in Utah that would carry billions of gallons of oil. Business interests cheered the ruling as a necessary check on a process that had become too burdensome, costly and slow, while environmentalists said it would allow agencies to ignore major environmental impacts, including the acceleration of climate change.

$=>$ *Why Texas's 'cut-throat' approach to net zero is paying off* : _July 2025_ : Bobby Helmers used to be an oilman, but those wells have long been plugges up. 'It's not that I was dissatisfied with the oil. It's just that production was depleting. They became no longer economically feasible'. Now, instead, the 84-year-old Trump voter has six wind turbines spinning on his ranch. The result is an abundance of clean, cheap power fuelling strong economic growth in Texas, with many Republicans supportive of the shift away from oil. However, their backing is now being put to the test as Donald Trump wages war on America’s clean energy sector. After returning to the White House with a promise to “drill, baby, drill”, the US president has dismissed
wind farms as “junk” and referred to them dismissively as “windmills”.

== UK Climate Policy

$=>$ *How the political consensus on climate change has shattered* : _May 2025_ : When the UK became the first major economy in the world to commit to reducing its carbon emissions to net zero by 2050, there was so little disagreement among MPs it was simply 'nodded through' without a vote. Six years on, the political climate is very different, the consensus at Westminster has shattered and reaching net zero is fast becoming a political dividing line. In 2019, when the target to reach net zero carbon emissions by 2050 was set, public concern about climate change was very visible. What has changed, he says, is the conversation around it which, after the rising cost of living and the war in Ukraine, has switched to "how does this reflect on people's pockets and does it make people think the country is safer as a result?" Undoubtedly, part of the rise in the conversation about climate targets has been driven by the rise of Reform, which has made what it calls "net stupid zero" one of its major campaign issues.

$=>$ *No gas boiler ban as Ed Miliban opts for 'carrots not sticks'* : _October 2025_ : Homeowners will not be forced to ditch their gas boiler for a heat pump, Ed Miliband has announced, as he attempted to see off a consumer backlash over the transition to clean energy. Under past Conservative government plans, the sale of new gas boilers was to be banned from 2035 and homes made to install a heat pump instead. But the move was opposed by a majority of voters due to concerns that the new technology could prove more expensive. In an announcement as part of a Labour plan to reduce UK emissions over the next ten years, Miliband confirmed that the boiler ban was being ditched in favour of an incentivised approach to the green transition. Instead of a ban there will be a series of incentives for homes to switch to heat pumps including extending £7,500 grants for the next five years.

== International Action

$=>$ *Has the world's climate summit lost its way ?* : _November 2025_ : Ahead of this year’s Cop, the UN secretary-general António Guterres delivered the stark admission that humanity has failed to keep global heating within 1.5°C. Missing a headline target set ten years ago at Cop21 invited fresh questions about whether the institution is genuinely capable of driving meaningful progress. ndeed, 30 years on from its inception, the conference’s size is becoming unwieldy. What began as a forum for world leaders, scientists and diplomats has tilted steadily towards the interests of lobbyists. The summit floor is now crowded with representatives of oil, agribusiness, banking and mining, each presenting themselves as indispensable to tackling the crisis their industries helped create.

$=>$ *With Trump absent from COP30 talks, the wold moves on without U.S.* : _November 2025_ : At the mouth of the great Amazon, not all visitors were welcome. Indigenous protesters in the Brazilian port city of Belém, which is hosting an annual major U.N. climate summit, forced their way into the premises of the meetings earlier this week, clashing with security personnel. They denounced the predations of vast agribusinesses, oil barons and illegal miners complicit in the deforestation of their Amazonian homelands. For some in Belém, the global calamity that will entail is impossible to deny. “As a scientist, I’ve never had reason to be so concerned as I am today for the future we are facing,” Johan Rockstrom, director of the Germany-based Potsdam Institute for Climate Impact Research, said in a video message welcoming delegates to a pavilion at the summit on planetary science. “We’ll be approaching tipping points of irreversible changes undermining life support and will have impacts affecting billions of co-citizens around the world. We need climate action faster than ever. Scale and pace is the only currency that matters.” To no one’s surprise, not only is Trump a no-show at the ongoing summit in Brazil, but the White House also didn’t even dispatch a senior-level delegation — as other major emitters whose leaders are also absent, such as China and India, have.

== Climate Innovation :

-> Geoengineering\
-> Indoor farming

== Nature conservation

$=>$ *Inside the 'bitter' battle against UK's first new national park in years* : _January 2025_ : Galloway can reasonably claim to be Britain’s best kept secret: a stunning part of rural south-west Scotland overlooked by tourists. A plan to turn the area into the UK’s next national park would end its obscurity. Advocates hope the scheme will encourage more visitors to experience its deep forest, rolling hills and untouched coastline. But a vocal group of Galloway residents, farmers and landowners are dead against the idea – convinced it will backfire and ruin the region’s unspoiled beauty. She would have to clear up discarded tents, broken bottles and toilet waste left by wild campers. Brownlee does not want the same to happen to Galloway, which would be Scotland’s third national park: “It’s a magical place. People come here because it’s unspoiled. “Going out for a walk is a bit of an adventure here. We don’t need a quango coming in sanitising the area with lots of signs and footpaths and bringing in too many people.”

$=>$ *Rivers are increasingly being given legal rights. Now they need people who will defend these rights to court* : _March 2025_ : A district council in England has passed a motion to grant its local river the rights to flow freely, to be free from pollution and to enjoy its native biodiversity. The move by Lewes District Council in East Sussex to recognise the fundamental rights of the River Ouse is the first of its kind in the UK. This may mean appointing someone to represent the rights of the river. Who these representatives are, and how they think about nature and conservation, can be as important as the granting of these rights in the first place. Appointing representatives who care about their own personal and property interests would be a grave mistake, as would appointing anyone who prioritises the rights of humans to a healthy environment over a more intrinsic right of nature (remember: the idea is that the River Ouse has rights in itself and shouldn’t need to demonstrate its worth to humans).

$=>$ *Lynx in Scotland : why illegal attempts to reintroduce lost species are suprinsingly common* : _January 2025_ : For more than 500 years, no lynx had roamed the British countryside. That changed with the recent release of four of these large cats in the Cairngorm mountains of Scotland. This was an action that is widely assumed to be linked to attempts to reintroduce species that had been wiped out in Britain, as part of a wider rewilding movement. Supporters of these reintroductions typically want to atone for past extinctions, and want to create richer, more dynamic ecosystems. llicit and unregulated reintroductions matter. They can lead to new populations of previously missing species – there are over a thousand beavers living in the Tayside region of Scotland, for instance, widely thought to descend from beavers deliberately, and illegally, released in the early 2000s. Illicit and unregulated reintroductions can be controversial. Farmers and other land managers do not always take kindly to new species popping up on their land without warning or consultation.

= File 6 : Migration

== Introduction

$=>$ *The truth about immigration* : _September 2025_ : Across the rich world, almost every state faces a version of the same problem: their people are living longer and having fewer children. Immigration is how states have filled the gap. Most wealthy states now have more immigrants than ever before. David Bull, the chair of the rightwing populist party Reform UK, has himself described immigration as the “lifeblood” of the country. But politicians have a problem: immigration is the subject of fierce political opposition. Not all opposition to immigration is about prejudice — very few of us react well to sudden change, which is in part why opposition to immigration tends to be highest not in places with a lot of immigration, but where there has been a sudden increase in the rate of the change.

$=>$ *The new economics of immigration* : _March 2025_ : In one rich country after another, immigrants are blamed for society’s problems. Complaints about migrants are as old as Jacob’s trek into Egypt. They make three claims: that immigrants are taking houses from citizens; that, even if they work, they are bankrupting welfare systems and jumping the queue for public services; and that they are spoiling the culture that made the West prosperous. The old gripe, that economic migrants steal jobs or undercut wages, has not gone away but has lost much of its power over the past decade as labour markets have boomed. The new arguments are more plausible, and therefore more dangerous. Evidence has mounted that rents and prices rose as people entered Western housing markets choked by building restrictions, contributing to inflation. But the new nativists exaggerate how much of this was down to migration. Rules of thumb suggest that it accounts for a tenth or so of the 39% real-terms increase in rich- world house prices between 2013 and 2023. The next argument, about whether migrants pay their way, looks solid but is not. Numerous studies show how the fiscal effect of migration depends on migrants’ skills. Immigrants to the Netherlands pay more in taxes than they take out in benefits over their lifetime only if they have at least a bachelor’s degree. However, a simple accounting of money in versus money out is incomplete. Migrants do not just pay taxes themselves, but raise the productivity of companies and their fellow workers. That increases the economy-wide tax take. It is on cultural change that the nativist overreach is at its worst, because even the foundations of the argument are bad. The most respectable version of it is found in the literature about the “deep roots” of growth, which traces differences in the wealth of nations today to flows of migration from countries that were advanced or backward centuries ago. But like all claims about what makes countries rich or poor, the theory is plagued by small sample sizes and pesky counter-examples. Embarrassingly, it cannot easily explain the prosperity of the world’s biggest countries. America, with its history of relatively open borders, is far richer than its “deep roots” score would suggest; China and India are poorer. Deep-roots theory looks favourably on migrants from East Asia, but they too were demonised in the early 20th century by Americans.

== US Migration policy

$=>$ *Trump offers a Golden Ticket* : _September 2025_ : Enter the Trump Gold Card -- not a credit card but a new pathway to immigration, offering wealthy foreigners a fast track to permanent residency in the United States. Launched on Friday by executive order alongside a restrictive new update to the H-1B program, the Trump Gold Card offers potential immigrants a trade: In exchange for \$1 million plus processing fees, the government will give you an EB-1 or EB-2 visa. The administration is hoping to add an even more exclusive tier in the form of the \$5 million Trump Platinum Card, which would give recipients 270 days’ residency in the U.S. with no tax on non-U.S. income. The EB-1 and EB-2 are employment-based visas that have historically been reserved for foreigners of “extraordinary” and “exceptional” ability, among other highly qualified professionals; the number following EB denotes a recipient’s importance on the world stage. U.S. Citizenship and Immigration Services suggests that a Pulitzer Prize or an Olympic medal might be part of a winning EB-1 application (it seems to go to all- purpose celebrities, too, such as former supermodel Melania Trump); professionals with “advanced degrees” could consider applying for an EB-2. That the \$1 million Trump Gold Card now qualifies as “sufficient evidence that the individual will substantially benefit the United States” suggests that this administration thinks personal riches are a superpower of their own.

$=>$ *Donald Trump is victorious at the southern border* : _October 2025_ : In 1971 the barrier that separated San Diego from Tijuana was a bit of chicken wire. Even that was too much for Pat Nixon, who was First Lady at the time. When she visited the beach at the very south-western edge of California she decided she wanted to meet the Mexicans queuing to greet her. So she asked the mayor of Tijuana to tear down the fence. “I do hope that this will be a common beach,” she said. “Because we’re such good friends with Mexico, I don’t think we need a border.” Mr Trump is claiming victory on the issue that launched his political career a decade ago. “On our southern border, we have successfully repelled a colossal invasion,” he told the UN last month. Many border wonks are sceptical of the effectiveness of enforcement alone. They contend that the US-Mexico frontier is so long (1,950 miles or 3,145km) and the coyotes (people-smugglers) so wily, that people will always find new ways to cross. That argument has held up—until now. The Trump administration has thrown the entire might of the federal government behind stopping illegal immigration. Their approach “is layered, like an onion”, 

$=>$ *Trump is deporting fewer people than Obama. He's just louder and meaner.* : _July 2025_ : You have seen the blizzard of scary images — immigration agents taking parents away in front of their kids, masked officers raiding neighborhoods, men detained in remote centers — but here is the surprising fact behind the mayhem: Donald Trump has deported fewer people per month than Barack Obama did, and barely more than Joe Biden during a similar span last year. Trump’s deportation dragnet is less effective than those of his predecessors because it is chaotic, theatrical and detached from the systems that work. Rather than effectively coordinating with local law enforcement, following rules, laws and norms, or expanding and expediting legal processing, Trump has prioritized optics over outcomes. What his administration lacks in strategy, it tries to compensate for with spectacle — sweeping up schoolchildren, targeting families, broadcasting raids on social media.

== UK Migration policy

$=>$ *Keir Starmer in asylum crackdown as he vows to end 'golden ticket' for migrants* : _October 2025_ : Sir Keir Starmer has vowed to end “the golden ticket” of migrants who are granted asylum in the UK getting automatic rights to settle in the country or bring family members with them, as part of the government’s latest immigration crackdown. It comes after the prime minister made a dramatic U-turn over international human rights laws that have been criticised for making it harder to deport asylum seekers. t marks another major policy reversal by Sir Keir, a former human rights lawyer, who has defended the ECHR in the past. It also comes as the prime minister steps up his attacks on Reform UK leader Nigel Farage, dubbing the small boats he is trying to stop crossing the English Channel “Farage boats”.

== Climate Migration

$=>$ *Climate change threatens to displace many people* : _October 2025_ : Climate change doesn’t only alter the ways people live, work, and eat. It can also force them to leave their homes behind. Human beings have moved around the world for millennia. Those who do are often referred to as migrants. Some are called economic migrants, refugees, or displaced persons, or they take on other labels. Climate change’s consequences are worse in many less-developed countries with weak infrastructure and ongoing conflict. However, climate drives migration everywhere. In the United States, natural disasters, many worsened by climate change, displaced an estimated 3.2 million adults in 2022. By 2023, more than five hundred thousand of them had not returned to their original homes. So, although climate-related migration hits some countries and regions harder, it knows no borders. The researchers found that, if governments invest in climate mitigation and adaptation, they could drop the numbers of internally displaced people by 80 percent (to forty-four million). So, how does the world meet that goal? Simply paying attention to the connections between climate and migration, researching them, and raising awareness about them is one way to help. Experts have called for stronger recognition, among international development programs and other groups that are addressing global migration, of climate change’s role in displacement.

= File 7 : Health

== Weight Loss

$=>$ *In a world of addictive foods, we need GLP-1s* : _May 2025_ : hroughout my life I’ve been fat, thin and various sizes in between. Since I was a kid, I’ve gained and lost weight repeatedly, putting on 20 pounds, taking it off, putting on 30 pounds and then losing it again. It has been a cycle of despair. The fact that I’m a doctor, was a dean of two medical schools and ran the Food and Drug Administration for six and a half years was of no help to me. Like millions of others, I was caught between what the food industry has done to make the American diet unhealthy and addictive and what my metabolism could accommodate. We may now be at the brink of reclaiming our health. New and highly effective anti-obesity medications known as GLP-1s have revolutionized our understanding of weight loss and of obesity itself. . GLP-1s appear to modify addictive brain pathways that are activated by ultraformulated foods, helping people to change their body weight in a decisive way. Traditional dieting might result in a weight loss of 5 percent to 7 percent. The new GLP-1 drugs more than double that. Even so, these are not magic medications. Prescribing them without other interventions, like healthier eating, exercise and behavioral therapies aimed at developing other lasting lifestyle changes, isn’t good medical care. 

$=>$ *Why weigth-drugs alone won't make us healthy* : _September 2025_ : But for all the breakthroughs, governments are stuck. Caught between the pharmaceutical revolution on one side and a trillion-dollar food industry on the other, they face a defining question: Will we settle for treating obesity, or will we finally tackle its causes? Because here’s the uncomfortable truth: Weight-loss drugs are extraordinary, but they are not a solution on their own. GLP-1 drugs have been nothing short of miraculous for many. Originally designed for diabetes, they suppress appetite and help people lose 15–20% of their body weight. But here’s the dilemma: If governments focus on prescriptions instead of prevention, they risk hardwiring obesity into the next generation. We now know that ultra-processed foods (UPFs)—industrial combinations of refined starches, seed oils, sugars, additives, and flavorings—don’t just make us gain weight. They change our biology. They spike blood sugar, drive inflammation, disrupt satiety signals, and, in many cases, are engineered to keep us eating well past the point of fullness.

== Gene editing

$=>$ *For the first time, a CRISPR drug treats a child's unique mutation* : _May 2025_ : Within days after KJ was born in Philadelphia in August 2024 it was clear that something was wrong. He was not eating and slept too much. Blood tests revealed sky-high levels of ammonia, a toxic substance the body usually expels. Genome sequencing confirmed that he had a rare genetic disease called CPS1 deficiency, which often kills in infancy, and for which no good neonatal treatment exists. Then one of his doctors suggested something radical: a gene-editing drug designed specifically for him. His doctors believed they could produce a drug in months. Remarkably, their plan seems to have worked. KJ is now preparing to leave the hospital for the first time and go home to his family, after becoming the first person to be treated with a bespoke gene-10 editing therapy.

$=>$ *Your next pet could be a glowing rabbit* : _February 2025_ : Humans have been selectively breeding cats and dogs for thousands of years to make more desirable pets. A new startup called the Los Angeles Project aims to speed up that process with genetic engineering to make glow-in-the-dark rabbits, hypoallergenic cats and dogs, and possibly, one day, actual unicorns. The Los Angeles Project is the brainchild of biohacker Josie Zayner, who in 2017 publicly injected herself with the gene-editing tool Crispr during a conference in San Francisco and livestreamed it. “I want to help humans genetically modify themselves,” she said at the time. She’s also given herself a fecal transplant and a DIY Covid vaccine and is the founder and CEO of The Odin, a company that sells home genetic-engineering kits. Now, Zayner wants to create the next generation of pets. “I think, as a human species, it’s kind of our moral prerogative to level up animals,” she says. The team has used Crispr to add a gene to rabbit embryos so they produce green fluorescent protein, or GFP. Zayner says they’re aiming to transfer the engineered embryos to female rabbits this week. They won’t be the first glowing animals ever created. GFP is commonly used by scientists to visually track and monitor gene activity or cellular processes within an organism, often to study diseases. Researchers have previously made fluorescent rodents, monkeys, dogs, cats, and rabbits, but none of these animals were created for commercial purposes.

== Drugs

$=>$ *'All eyes are on Glasgow' : UK's first legal drug consumption room ready to open* : _January 2025_ : The UK’s first legal drug consumption room will open its doors in Glasgow after a 10-year battle to realise the pioneering facility. The Thistle will remain open 365 days a year from 9am to 9pm and allow some of the most vulnerable addicts in the city to take their own drugs in a clean and safe environment under the supervision of health professionals. “We know across the world that safe consumption makes a difference, but we need to demonstrate that it works within the confines of the UK, and indeed, the Misuse of Drugs Act,” he added

$=>$ *America was finally turning corner on opioids. Until now.* : _August 2025_ : Not so long ago, the scourge of opioids seemed unstoppable. More than 400,000 Americans died from drug overdoses between 2020 and 2023. But 2023 now appears to have been a turning point. Since then, annual overdose deaths have declined more than 25 percent, thanks partly to a creative public health campaign to expand access to treatments like Narcan and Suboxone. The crisis is finally easing. President Trump’s big domestic policy law threatens that progress. The law’s Medicaid cuts, which finance lower taxes for the wealthy, will deprive millions of Americans of health insurance. addicts are particularly vulnerable because of how many of them are on Medicaid. The program covers nearly half of non-elderly adults with an opioid addiction. Without insurance, many will drop out of treatment and relapse. Mr. Trump, Vice President JD Vance and other Republican leaders have rightly described opioids as a national tragedy that demands action. Instead of taking steps to continue the recent progress, however, they are undermining it

$=>$ *A dangerous new class of synthetic opioid is spreading* : _September 2025_ : Nitazenes are opioids, a family of chemicals that includes morphine and heroin as well as the much stronger fentanyl, which causes tens of thousands of deaths in America every year. Although measures of their potency vary, scientists estimate that nitazenes can be hundreds of times stronger than heroin, with some thought to be dozens of times stronger than fentanyl. But whereas heroin and fentanyl have long histories as medical analgesics and have therefore been extensively studied, hardly any research exists on nitazenes. With nitazene use rising around the world, and in particular in Australia and Europe, scientists are scrambling to gather data on how dangerous these new drugs are and who is at risk. The emerging picture is grim. In 2019, however, toxicologists conducting routine surveillance of the European drug market turned up one nitazene, isotonitazene, being sold directly to users on a dark corner of the internet. Many scientists studying nitazenes believe the explosion in recent years is a supply-side reaction to increased restrictions on other drugs. In the mid-2010s America boosted its attempts to crack down on new fentanyl analogues and their precursors, and persuaded other countries to do the same.

== Make America Healthy Again

$=>$ *Will MAHA change America* : _August 2025_ : The movement that helped make Robert F. Kennedy Jr. the secretary of health and human services converged politically with right-wing populism only in the last few years, but in spirit the holistic, outsider critique of modern medicine had a lot in common with MAGA populism long before the “MAHA” neologism came along. Like populism, the MAHA movement spoke to widely shared frustrations with a medical establishment that didn’t seem to have answers to persistent problems and left people who felt failed by the system feeling unheard and disdained. R.F.K. Jr. entered office promising to address two great challenges in American public health, the spread of obesity and the resilience of chronic illness. The roots of the American weight problem are endlessly debated, with car culture and suburbia offered as non-dietary explanations for why we’re fatter than the Europeans. The anti-corporate critique of how we grow and make and sell our food nonetheless has a certain plausibility, and the MAHA impulse to push Americans away from chemicals and processed foods seems like an experiment worth trying. underplays pharmaceutical solutions and imagines that public health is just a matter of stripping away late- modern toxins and restoring ruddy pre-1960s vigor. Certainly modernity has its toxic side and nature has a lot of wisdom. But the natural world also has a lot of ways of killing us and torturing us, which human ingenuity enables us to overcome. And the pre-1960s landscape yielded better health for some people and premature death for many, many others. So you need to strike a balance, where you tout organic produce and whole grains and exercise regimes to fight obesity … but also embrace the revolutionary potential of the new wave of weight-loss drugs. Or where you look for the roots of chronic illnesses in chemicals and pollutants …. but also remain open to the possibility that a lot of chronically sick people are dealing with infections that might be cured with the right mix of prescription drugs. 

$=>$ *US cuts universal childhood vaccine recommendations, including Covid and hepatitis* : _January 2026_ : An overhaul of US childhood immunisation guidelines has dropped the number of diseases children should be vaccinated against from 17 to 11. US President Donald Trump praised the new recommendation saying it was "rooted in the gold standard of science". However, the American Academy of Pediatrics criticised the recommendation, describing it as "dangerous and unnecessary." The overhaul is the latest sweeping policy change made under the Trump administration spearheaded by health secretary Robert F Kennedy Jr.

$=>$ *Florida moves to end all school vaccine mandates, first in nation to do so* : _September 2025_ : Florida’s surgeon general on Wednesday announced plans to end all state vaccine mandates, including for children to attend schools, which would make it the first state to completely withdraw from a practice credited with boosting vaccination rates and controlling the spread of infectious diseases. The Trump administration and Health and Human Services Secretary Robert F. Kennedy Jr., the founder of an anti-vaccine organization, have been pushing to upend U.S. vaccine policy. Florida’s move underscores the deepening political fault lines over vaccines, a divide certain to polarize parents, communities, lawmakers and health providers across red and blue states

== UK Assisted Dying bill

$=>$ *What's happening with the assisted dying bill ?* : _December 2025_ : t was more than a year ago that MPs first gave their backing to proposed legislation which would introduce assisted dying in England and Wales, in an historic House of Commons vote. In its current form, the Terminally Ill Adults (End of Life) Bill would allow people over the age of 18, who are expected to die within six months, to be given help to end their own life, subject to certain safeguards.

= File 8 : Education

== College degrees

$=>$ *College cant' be only for the rich* : _January 2025_ : Academia has become one of Washington’s favorite political punching bags. Colleges and universities are often accused of obsessing over race in admissions, peddling radical and anti-American ideologies and churning out too many students with impractical degrees and poor job prospects. Higher education has become increasingly unaffordable. Some of our nation’s leaders appear to have lost sight of the importance of universities and have undermined their promise.  This has happened slowly and indirectly — a seeming unwillingness to appropriate adequate funds, a tax slipped discreetly into a lengthy budget document, a selective insistence on fiscal discipline over providing more help for working- and middle-class students to secure their places on American campuses. with average annual price tags of \$11,610 in tuition and fees to attend an in-state public four-year college and \$43,350 for a private four-year school, college places a heavy financial burden on students and their families. Funding for the Pell Grant — the largest federal grant program for undergraduates and a vehicle for giving need-based financial aid to millions of students — has failed to keep up with the costs of attending college, which have outpaced inflation and wage increases.

$=>$ *Is your master's degree useless ?* : _November 2024_ : In America close to 40% of workers with a bachelor’s also boast a postgraduate credential of some sort. In the decade to 2021 the number of postgraduate students there increased by 9% even as undergraduates fell by 15%. PhDs required by academics and long professional degrees of the sort needed by doctors an  lawyers are becoming more popular. But master’s courses still account for most of the growth. In part this has been driven by employers demanding higher qualifications as jobs in science and technology, in particular, grow more complex. Since 2000 the cost of postgraduate study in America has more than tripled in real terms, according to the Centre on Education and the Workforce at Georgetown University. The median borrower now acquires around \$50,000 in debt while completing their second degree. It has been found that by the age of 35, master’s graduates earn no more than those with just a bachelor’s (after accounting for their better-off backgrounds and higher previous attainment)

== Private Education

$=>$ *Should you send your children to private school ?* : _June 2023_ : In many rich countries, traditional private schooling is in decline. Recent evidence suggests that for most privately schooled children in Britain and those who attend elite private institutions in America, the advantages of an expensive education remain robust. Private schools in Britain serve around 6.5% of kids, about the same share as they did in the 1960s, America’s ones teach about 9% of children. Measuring what benefits flow from these outlays matters both to critics of private schooling—who accuse posh schools of perpetuating elites—and to those who pay for it. At first glance, the pay-offs are clear: all around the rich world privately educated pupils do better in exams, go to better universities and end up with better-paid jobs. But some of that success derives from advantages outside the classroom, such as having wealthy, encouraging or intelligent parents. Understanding the boost from private education involves comparing pupils’ fortunes with those of otherwise similar peers in government schools. Good research of this sort is easiest to find in Britain. By the time they turn 25 Britons with private education earn 17% more than other workers from similar homes, according to a study from 2015. The pay premium widens by the age of 42, according to earlier research, to around 21% for women and 35% for men. In part this is because privately schooled people are more likely to enter high-earning professions, such as finance. 

$=>$ *Voucher push it reshaping private school education, study finds* : _September 2025_ : Some private schools are raising tuition, and others are able to enroll more students as publicly financed voucher programs begin to reshape education across the country. But the biggest beneficiaries of the new programs so far may be families whose children were already attending private schools, according to a new study. Private schools in states with broad access to vouchers increased tuition by 5 to 10 percent more than private schools in states without such policies, according to the paper, while enrollment increased by 3 to 4 percent more than in other states

== Technology and learning

$>$ *AI-driven education; founded in Texas and coming to a school near you* : _July 2025_ : Alpha-school, a franchise of private schools in Texas, created by and influencer. In there, there's no teachers, only AI and guides. The guides are there to ensure the students are correctly using the AIs

$=>$ *Generation AI: fears of 'social divide' unless all children learn computing skills* : _January 2026_ : With how AI is growing, it's important to teach students about how tu use it. To ensure that every student's skillset it growing in accordance to the times we're living, Autralia has put on a AI literacy plan. Australia's authorities consider it's important for the future of children to teach them how to use AI in order to avoir inequality betwee, them.

$=>$ *When kids adopt new technologies, hype can turn to backlash* : _December 2025_ : The hype cycle : a repeating cycle whenver a new technology appears : 1. People thinks it's a great technology and it needs to be put in every part of our lives and in particular in the educational field. This is where AI is currently. 2. People starts realising that the tech is really not as important as they thought and they realise the multiple drawbacks that comes with its using. 3. The tech gets banned in places it was volontarily put in the first place, in school for instance. This is where smartphones are currently. This hype cycle was directly seen in Australia, they are currently pushing for the developpement of AI, but they did the same before with smartphones. They put smartphones in class because it could 'help people socialize" and then a few years later they rolled it back, and it might happen exactly the same with AI.